FILES=extension.js connmanApplet.js connmanAgent.js connmanInterface.js \
	logger.js technology.js service.js metadata.json stylesheet.css
PREFIX=~/.local/share/
PATH=gnome-shell/extensions/ConnmanApplet@jaakko.hannikainen.intel.com

install:
	/usr/bin/mkdir -p ${PREFIX}${PATH}
	/usr/bin/cp ${FILES} ${PREFIX}${PATH}
